#!/bin/sh
set -e
# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask neutron-l3-agent.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled neutron-l3-agent.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable neutron-l3-agent.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state neutron-l3-agent.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/neutron-l3-agent" ]; then
		update-rc.d neutron-l3-agent defaults >/dev/null
	fi
	if [ -x "/etc/init.d/neutron-l3-agent" ] || [ -e "/etc/init/neutron-l3-agent.conf" ]; then
		invoke-rc.d neutron-l3-agent start || true
	fi
fi
# End automatically added section
