#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/neutron-linuxbridge-agent" ] || [ -e "/etc/init/neutron-linuxbridge-agent.conf" ]; then
	invoke-rc.d neutron-linuxbridge-agent stop || true
fi
# End automatically added section
