#!/bin/sh

set -e

case $1 in
        remove|purge)
                invoke-rc.d neutron-server stop
esac

# Automatically added by dh_installinit
if [ -x "/etc/init.d/neutron-server" ] || [ -e "/etc/init/neutron-server.conf" ]; then
	invoke-rc.d neutron-server stop || true
fi
# End automatically added section

