#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/neutron-dhcp-agent" ] || [ -e "/etc/init/neutron-dhcp-agent.conf" ]; then
	invoke-rc.d neutron-dhcp-agent stop || true
fi
# End automatically added section
